[package]
name = "dirman_rpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
env_logger = "0.10.1"
rusqlite = "0.30.0"
libsqlite3-sys = { version = "0.27.0", features = ["bundled"]}